"""Build the knowledge-base corpus.

Two kinds of article end up in corpus/:

  1. Incident-derived, generated from the pinned source dataset. Each source
     incident becomes one article: symptom, diagnosis, root cause, resolution.
     Retrieval over these behaves realistically -- including badly, because
     several incidents in a family share a title and retrieval has to choose
     between near-duplicate documents.

  2. Policy and how-to, hand-written, copied from policy/.

The second kind exists because a corpus built only from incidents cannot
answer a question like "how do I reset my password" -- there is no incident
that documents the normal procedure, only incidents where it went wrong. A
real knowledge base has both, and without the policy half every demo question
has to be incident-shaped.

All free text is redacted with the dataset's own PII answer key. A real KB
article would not carry the reporter's name or employee ID, and a corpus full
of PII would trip the output guard on every RAG answer.

    python scripts/build_corpus.py
"""

import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.build_tool_data import FAMILY_TO_SERVICE, TICKETS_PER_FAMILY, load_source
from scripts.fetch_dataset import DATASET_ID, DATASET_REVISION
from scripts.redact import load_pii_key, redact

ROOT = Path(__file__).resolve().parents[1]
CORPUS_DIR = ROOT / "corpus"
# Hand-written policy and how-to articles. They live outside corpus/ because
# this script deletes and rebuilds corpus/, and they are the source of truth
# rather than generated output.
POLICY_DIR = ROOT / "policy"

# Three per family, 14 families, so 42 articles -- inside the spec's 30-50.
# Taken after the slice build_tool_data.py used for lookup_ticket, so the KB
# and the ticket tool describe different incidents and it stays obvious which
# tool answered a question.
ARTICLES_PER_FAMILY = 3


def article_markdown(row, service: str, pairs) -> str:
    """Render one incident as a KB article."""
    steps = "\n".join(
        f"{n}. {redact(step, pairs)}"
        for n, step in enumerate(row.resolution["steps"], start=1)
    )
    return f"""# {redact(row.title, pairs)}

**Service:** {service}
**Source incident:** {row.record_id}
**Priority:** {row.priority}

## Symptom

{redact(row.description, pairs)}

## Diagnosis

{redact(row.diagnostics["summary"], pairs)}

## Root cause

{redact(row.root_cause, pairs)}

## Resolution

{steps}
"""


def copy_policy_articles() -> list[str]:
    """Copy the hand-written policy articles into corpus/."""
    if not POLICY_DIR.exists():
        return []
    names = []
    for path in sorted(POLICY_DIR.glob("*.md")):
        shutil.copyfile(path, CORPUS_DIR / path.name)
        names.append(path.name)
    return names


def sources_markdown(written: list[tuple[str, str]], policy: list[str]) -> str:
    """Attribution, per file. Learners take this repo home."""
    rows = "\n".join(f"| `{name}` | {record_id} |" for name, record_id in written)
    policy_rows = "\n".join(f"| `{name}` |" for name in policy)
    return f"""# Corpus sources

This corpus has two halves, and the difference matters when you are judging an
answer: **{len(written)} incident-derived articles** generated from the dataset
below, and **{len(policy)} policy and how-to articles written by hand**.

The hand-written half exists because incident records cannot answer "how do I
do X" -- they only record occasions when X went wrong. They are authored, not
derived from any dataset, and they describe the same synthetic environment
(Okta, GlobalProtect, Intune, Software Center, corplabs.com) so that a policy
answer and an incident answer do not contradict each other.

## Hand-written policy and how-to articles

Source of truth is `policy/` in the repository root. Edit them there --
editing the copies in `corpus/` is pointless, the builder overwrites them.

| File |
|---|
{policy_rows}

## Incident-derived articles

Every article here is generated by `scripts/build_corpus.py` from:

**[{DATASET_ID}](https://huggingface.co/datasets/{DATASET_ID})**
- Licence: **MIT**, (c) 2026 Alexander Meau
- Revision: `{DATASET_REVISION}`
- All records are synthetic. No real personal data.

Free text is redacted using the dataset's own `pii.json` answer key, so the
corpus is clean by construction rather than by our regexes being good. See
`ATTRIBUTION.md` for the full provenance note and the two caveats worth
saying out loud during the session.

Do not edit these files by hand -- rerun the builder.

| File | Source incident |
|---|---|
{rows}
"""


def main() -> None:
    frame = load_source()
    pii_key = load_pii_key()

    if CORPUS_DIR.exists():
        # Rebuild from scratch, or a renamed article would linger and get
        # indexed twice.
        shutil.rmtree(CORPUS_DIR)
    CORPUS_DIR.mkdir()

    written: list[tuple[str, str]] = []
    for family in sorted(FAMILY_TO_SERVICE):
        subset = frame[frame.family == family].sort_values("record_id")
        # Skip the incidents lookup_ticket already serves.
        start = TICKETS_PER_FAMILY
        chosen = subset.iloc[start : start + ARTICLES_PER_FAMILY]
        for _, row in chosen.iterrows():
            name = f"{row.record_id.lower()}.md"
            text = article_markdown(
                row, FAMILY_TO_SERVICE[family], pii_key[row.record_id]
            )
            (CORPUS_DIR / name).write_text(text)
            written.append((name, row.record_id))

    policy = copy_policy_articles()
    (CORPUS_DIR / "SOURCES.md").write_text(sources_markdown(written, policy))

    everything = [name for name, _ in written] + policy
    total = sum(len((CORPUS_DIR / name).read_text()) for name in everything)
    print(f"Wrote {len(everything)} articles to corpus/ ({total:,} characters)")
    print(f"  {len(written)} incident-derived, {len(policy)} hand-written policy")
    print("  plus corpus/SOURCES.md with per-file attribution")


if __name__ == "__main__":
    main()
